name: lint

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [ 7.1, 7.2, 7.3, 7.4 ]

    name: Lint code

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring
          coverage: pcov
          tools: prestissimo, php-cs-fixer, phpunit

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-composer
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ matrix.php-version }}-composer-${{ hashFiles('composer.json') }}
            ${{ matrix.php-version }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Execute linter
        run: php-cs-fixer fix --dry-run --format=txt --diff --verbose

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover cov.xml --coverage-text
